spring:
  datasource: 
    hikari:
      pool-name: hikari-cp
      #jdbc-url: jdbc:sqlserver://localhost;instance=SQLEXPRESS;databaseName=JamesBlogProject_DB;useLOBs=false
      jdbc-url: jdbc:sqlserver://localhost:1433;databaseName=JamesBlogProject_DB;useLOBs=false
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: sa
      password: 1234
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 50
      maxLifetime:  30000
      idleTimeout:  60000
      connectionTimeout:  60000
      validationTimeout: 50000
      autoCommit : true
server:
  servlet:
    session:
      timeout: 60m      
  port: 8888
mybatis:
  configuration:
    map-underscore-to-camel-case: false
